name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo and submodules
      uses: actions/checkout@v3
      with:
        lfs: 'true'
        submodules: recursive
    
    - name: Install dependencies
      run: sudo apt-get install libx11-dev libxext-dev libxv-dev libxrender-dev

    - name: checkout premake5
      uses: actions/checkout@v3
      with:
        repository: premake/premake-core
        path: premake-build

    - name: Build premake5
      run: |
        cd premake-build
        make -f Bootstrap.mak linux CONFIG=release
        cp bin/release/premake5 ../
        cd ..
        rm -Rf premake-build

    - name: Generate build files
      run: | 
        ls
        make --version
        ./premake5 gmake

    - name: Build
      run: make game

    - name: Run test
      run: make test

    - name: Archive resulting game binary
      uses: actions/upload-artifact@v3
      with:
        name: game-bin
        path: bin/Debug/game
        retention-days: 1

