name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo and submodules
      uses: actions/checkout@v3
      with:
        lfs: 'true'
        submodules: recursive
    
    - name: Install dependencies
      run: sudo apt-get install libx11-dev libxext-dev libxv-dev libxrender-dev premake

    - name: Generate build files
      run: premake5 gmake

    - name: Build
      run: make game

    - name: Run test
      run: make test

    - name: Archive resulting game binary
      uses: actions/upload-artifact@v3
      with:
        name: game-bin
        path: bin/Debug/game
        retention-days: 1

