name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install depenencies
      run: sudo apt-get install libx11-dev

    - name: build
      run: make game

    - name: Run test
      run: make test
